---

version: '3.3'

services:
  keycloak:
    container_name: keycloak-container
    command: start --hostname-strict=false --log-level=WARNING --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - KC_LOG_LEVEL=ALL
      - KC_DB_URL_HOST=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_LOGLEVEL=WARN
      - KC_HTTP_ENABLED=true
    restart: unless-stopped
    ports:
    - 5050:8080
    depends_on:
    - postgres
    volumes:
        - ../themes/:/opt/keycloak/themes/
  postgres:
    container_name: postgres-container
    image: postgres:15.1
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_USER=keycloak
    restart: unless-stopped

volumes:
  postgres-data:
